### ISSUE TITLE
Currently no way to store 43

### ISSUE THREAD

**Issue by tecknut** [brendan-fahy/MultiThreaded43Store#1]
Hi I've been trying to implement multi threaded 43 store but have been unsuccessful in storing 43.

I think I might have tracked the issue down, and I've love to submit a pull request. But you haven't allowed forking. 

Could you add permissions for public contributions?

Thanks

**Comment by brendan-fahy** [comment]
Thanks for reporting this. I've added a file to the repo now so you should be able to fork it. Hopefully that solves the problem.

Happy 43-ing.
